networks:
  xpd-network:
    external: false

services:
  xpd-gateway:
    image: ghcr.io/randomairborne/experienced:latest
    build:
      context: .
      dockerfile: ./xpd-gateway/Dockerfile
    restart: unless-stopped
    networks:
      - xpd-network
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://app:app@postgres:5432/app"
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    restart: unless-stopped
    networks:
      - xpd-network
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app
    volumes:
      - ./db-data:/var/lib/postgresql
